create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  username text unique,
  avatar_url text,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint profiles_username_format check (
    username is null or username ~ '^[A-Za-z0-9_-]{3,24}$'
  )
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  title text not null,
  body text,
  image_path text not null,
  thumb_path text,
  captured_at timestamptz,
  exact_lat double precision not null,
  exact_lng double precision not null,
  public_lat double precision not null,
  public_lng double precision not null,
  privacy_mode text not null default 'approx' check (privacy_mode in ('exact', 'approx')),
  place_name text,
  country_name text,
  region_name text,
  city_name text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  review_note text,
  approved_at timestamptz,
  approved_by uuid,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint posts_user_id_fkey foreign key (user_id) references public.profiles (id) on delete cascade,
  constraint posts_approved_by_fkey foreign key (approved_by) references public.profiles (id) on delete set null,
  constraint posts_title_length check (char_length(title) between 1 and 80),
  constraint posts_body_length check (body is null or char_length(body) <= 1000),
  constraint posts_exact_lat_range check (exact_lat between -90 and 90),
  constraint posts_exact_lng_range check (exact_lng between -180 and 180),
  constraint posts_public_lat_range check (public_lat between -90 and 90),
  constraint posts_public_lng_range check (public_lng between -180 and 180)
);

create table if not exists public.post_photos (
  post_id bigint not null references public.posts (id) on delete cascade,
  image_path text not null,
  thumb_path text,
  sort_order integer not null,
  created_at timestamptz not null default timezone('utc', now()),
  primary key (post_id, sort_order),
  constraint post_photos_sort_order_range check (sort_order >= 0),
  constraint post_photos_image_path_unique unique (post_id, image_path)
);

create table if not exists public.post_revisions (
  id bigint generated by default as identity primary key,
  post_id bigint not null,
  user_id uuid not null,
  title text not null,
  body text,
  image_path text not null,
  thumb_path text,
  captured_at timestamptz,
  exact_lat double precision not null,
  exact_lng double precision not null,
  public_lat double precision not null,
  public_lng double precision not null,
  privacy_mode text not null default 'approx' check (privacy_mode in ('exact', 'approx')),
  place_name text,
  country_name text,
  region_name text,
  city_name text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  review_note text,
  reviewed_at timestamptz,
  reviewed_by uuid,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint post_revisions_post_id_fkey foreign key (post_id) references public.posts (id) on delete cascade,
  constraint post_revisions_user_id_fkey foreign key (user_id) references public.profiles (id) on delete cascade,
  constraint post_revisions_reviewed_by_fkey foreign key (reviewed_by) references public.profiles (id) on delete set null,
  constraint post_revisions_title_length check (char_length(title) between 1 and 80),
  constraint post_revisions_body_length check (body is null or char_length(body) <= 1000),
  constraint post_revisions_exact_lat_range check (exact_lat between -90 and 90),
  constraint post_revisions_exact_lng_range check (exact_lng between -180 and 180),
  constraint post_revisions_public_lat_range check (public_lat between -90 and 90),
  constraint post_revisions_public_lng_range check (public_lng between -180 and 180)
);

create table if not exists public.post_revision_photos (
  revision_id bigint not null references public.post_revisions (id) on delete cascade,
  image_path text not null,
  thumb_path text,
  sort_order integer not null,
  created_at timestamptz not null default timezone('utc', now()),
  primary key (revision_id, sort_order),
  constraint post_revision_photos_sort_order_range check (sort_order >= 0),
  constraint post_revision_photos_image_path_unique unique (revision_id, image_path)
);

create table if not exists public.post_likes (
  post_id bigint not null references public.posts (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  primary key (post_id, user_id)
);

create index if not exists posts_status_created_at_idx
  on public.posts (status, created_at desc);

create index if not exists posts_public_point_idx
  on public.posts (public_lat, public_lng);

create index if not exists post_photos_post_id_sort_order_idx
  on public.post_photos (post_id, sort_order);

create unique index if not exists post_revisions_one_pending_idx
  on public.post_revisions (post_id)
  where status = 'pending';

create index if not exists post_revisions_status_created_at_idx
  on public.post_revisions (status, created_at desc);

create index if not exists post_revision_photos_revision_id_sort_order_idx
  on public.post_revision_photos (revision_id, sort_order);

create index if not exists post_likes_user_id_created_at_idx
  on public.post_likes (user_id, created_at desc);

insert into public.post_photos (post_id, image_path, thumb_path, sort_order, created_at)
select id, image_path, thumb_path, 0, created_at
from public.posts
where image_path is not null
on conflict (post_id, sort_order) do nothing;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row
execute procedure public.set_updated_at();

drop trigger if exists set_posts_updated_at on public.posts;
create trigger set_posts_updated_at
before update on public.posts
for each row
execute procedure public.set_updated_at();

drop trigger if exists set_post_revisions_updated_at on public.post_revisions;
create trigger set_post_revisions_updated_at
before update on public.post_revisions
for each row
execute procedure public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id)
  values (new.id)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.post_photos enable row level security;
alter table public.post_revisions enable row level security;
alter table public.post_revision_photos enable row level security;
alter table public.post_likes enable row level security;

drop policy if exists "profiles_select_self" on public.profiles;
create policy "profiles_select_self"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

drop policy if exists "profiles_insert_self" on public.profiles;
create policy "profiles_insert_self"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "profiles_update_self" on public.profiles;
create policy "profiles_update_self"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "posts_select_approved" on public.posts;
create policy "posts_select_approved"
on public.posts
for select
to anon, authenticated
using (status = 'approved' or auth.uid() = user_id);

drop policy if exists "posts_insert_self" on public.posts;
create policy "posts_insert_self"
on public.posts
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "posts_update_self" on public.posts;
create policy "posts_update_self"
on public.posts
for update
to authenticated
using (auth.uid() = user_id and status = 'pending')
with check (auth.uid() = user_id and status = 'pending');

drop policy if exists "post_photos_select_visible" on public.post_photos;
create policy "post_photos_select_visible"
on public.post_photos
for select
to anon, authenticated
using (
  exists (
    select 1
    from public.posts
    where posts.id = post_photos.post_id
      and (posts.status = 'approved' or auth.uid() = posts.user_id)
  )
);

drop policy if exists "post_photos_insert_self" on public.post_photos;
create policy "post_photos_insert_self"
on public.post_photos
for insert
to authenticated
with check (
  exists (
    select 1
    from public.posts
    where posts.id = post_photos.post_id
      and posts.user_id = auth.uid()
      and posts.status = 'pending'
  )
);

drop policy if exists "post_revisions_select_self" on public.post_revisions;
create policy "post_revisions_select_self"
on public.post_revisions
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "post_revisions_insert_self" on public.post_revisions;
create policy "post_revisions_insert_self"
on public.post_revisions
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "post_revisions_update_self" on public.post_revisions;
create policy "post_revisions_update_self"
on public.post_revisions
for update
to authenticated
using (auth.uid() = user_id and status = 'pending')
with check (auth.uid() = user_id and status = 'pending');

drop policy if exists "post_revision_photos_select_self" on public.post_revision_photos;
create policy "post_revision_photos_select_self"
on public.post_revision_photos
for select
to authenticated
using (
  exists (
    select 1
    from public.post_revisions
    where post_revisions.id = post_revision_photos.revision_id
      and post_revisions.user_id = auth.uid()
  )
);

drop policy if exists "post_revision_photos_insert_self" on public.post_revision_photos;
create policy "post_revision_photos_insert_self"
on public.post_revision_photos
for insert
to authenticated
with check (
  exists (
    select 1
    from public.post_revisions
    where post_revisions.id = post_revision_photos.revision_id
      and post_revisions.user_id = auth.uid()
      and post_revisions.status = 'pending'
  )
);

drop policy if exists "post_likes_select_self" on public.post_likes;
create policy "post_likes_select_self"
on public.post_likes
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "post_likes_insert_self_approved" on public.post_likes;
create policy "post_likes_insert_self_approved"
on public.post_likes
for insert
to authenticated
with check (
  auth.uid() = user_id
  and exists (
    select 1
    from public.posts
    where posts.id = post_likes.post_id
      and posts.status = 'approved'
  )
);

drop policy if exists "post_likes_delete_self" on public.post_likes;
create policy "post_likes_delete_self"
on public.post_likes
for delete
to authenticated
using (auth.uid() = user_id);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'fumo',
  'fumo',
  false,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif']
)
on conflict (id) do update
set public = excluded.public;

drop policy if exists "fumo_upload_own_folder" on storage.objects;
create policy "fumo_upload_own_folder"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'fumo'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "fumo_read_own_folder" on storage.objects;
create policy "fumo_read_own_folder"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'fumo'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "fumo_delete_own_folder" on storage.objects;
create policy "fumo_delete_own_folder"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'fumo'
  and (storage.foldername(name))[1] = auth.uid()::text
);

-- After running this schema, manually promote the first admin:
-- update public.profiles set role = 'admin' where username = 'your_admin_id';
